# Generated by Django 3.2 on 2021-04-15 04:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='attendance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='member',
            name='expiredate',
            field=models.DateField(default=datetime.datetime(2021, 5, 15, 10, 25, 52, 951248), max_length=40),
        ),
    ]
